CREATE TABLE "roles" (
  "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE
);

CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" int NOT NULL,
  "full_name" text,
  "login" text UNIQUE NOT NULL,
  "password" text NOT NULL
);

CREATE TABLE "authors" (
  "author_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "genres" (
  "genre_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "publishers" (
  "publisher_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "books" (
  "book_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "article" text UNIQUE NOT NULL,
  "title" text NOT NULL,
  "author_id" int NOT NULL,
  "genre_id" int NOT NULL,
  "publisher_id" int NOT NULL,
  "year" int,
  "price" numeric,
  "discount_price" numeric,
  "is_on_sale" boolean,
  "stock" int,
  "description" text,
  "cover_path" text
);

CREATE TABLE "pickup_points" (
  "pickup_point_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "address" text UNIQUE NOT NULL
);

CREATE TABLE "orders" (
  "order_id" int PRIMARY KEY,
  "user_id" int,
  "pickup_point_id" int,
  "order_date" date,
  "delivery_date" date,
  "receive_code" text,
  "status" text
);

CREATE TABLE "order_details" (
  "detail_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "book_id" int NOT NULL,
  "quantity" int NOT NULL
);

COMMENT ON COLUMN "roles"."name" IS 'role name';

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role_id");

ALTER TABLE "books" ADD FOREIGN KEY ("author_id") REFERENCES "authors" ("author_id");

ALTER TABLE "books" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("genre_id");

ALTER TABLE "books" ADD FOREIGN KEY ("publisher_id") REFERENCES "publishers" ("publisher_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("pickup_point_id") REFERENCES "pickup_points" ("pickup_point_id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("book_id");
